/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ozgeburak.yazilimlaboratuvari1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author burak
 */
public class SecimEkrani extends javax.swing.JPanel {
    BufferedImage menuArkaplan; 
    Timer tick; 
    Thread arkaplanDongu;
    
    static BufferedImage altin;
    static BufferedImage bulut1,bulut2,bulut3,bulut4,bulut5;
    
    ArrayList<MenuGrafigi> bulutlar;
    ArrayList<MenuGrafigi> altinlar;
    Random r;
    
    /**
     * Creates new form SecimEkrani
     */
    public SecimEkrani() {
        this.setPreferredSize(new Dimension(Oyun.pencereGenislik, Oyun.pencereYukseklik));
        //SecimMenusu.setOpaque(false);
        r = new Random();
        
        try {
            initComponents();
            
            //SecimMenusu.setBackground(new Color(255, 255, 255, 0));
            
        menuArkaplan = ImageIO.read(new File("kaynaklar/MenuArkasi.png"));
        } catch (IOException ex) {
            Logger.getLogger(SecimEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setBackground(new Color(141,183,242));
        
         try {
            altin = ImageIO.read(new File("kaynaklar/altin2x.png"));
            bulut1 = ImageIO.read(new File("kaynaklar/bulut1.png"));
            bulut2 = ImageIO.read(new File("kaynaklar/bulut2.png"));
            bulut3 = ImageIO.read(new File("kaynaklar/bulut3.png"));
            bulut4 = ImageIO.read(new File("kaynaklar/bulut4.png"));
            bulut5 = ImageIO.read(new File("kaynaklar/bulut5.png"));
           
        } catch (IOException ex) {
            Logger.getLogger(MenuGrafigi.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         bulutlar = new ArrayList<MenuGrafigi>();
         altinlar = new ArrayList<MenuGrafigi>();
         
         for(int i = 0; i < 10; i++){
             bulutlar.add(new MenuGrafigi(r.nextInt(1280), r.nextInt(720),"bulut"));
         }
         
         for(int i = 0; i < 50; i++){
             altinlar.add(new MenuGrafigi(-200 + r.nextInt(1280+200), -1 * r.nextInt(720),"altin"));
         }
         
         tick = new Timer();
         arkaplanDongu = new Thread(){
             @Override
             public void run(){
                 while(true){
                 for(MenuGrafigi altin :  altinlar){
                    altin.guncelle();
                }
                 
                       for(MenuGrafigi bulut :  bulutlar){
                    bulut.guncelle();
                }
                 repaint();
                try {
                    Thread.sleep(1000/60);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SecimEkrani.class.getName()).log(Level.SEVERE, null, ex);
                }
                //System.out.println("test");
                 }
                
                
            }
         };
         arkaplanDongu.start();
       

    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawRect(SecimMenusu.getX(),SecimMenusu.getY(),SecimMenusu.getWidth(),SecimMenusu.getHeight());
        
   
        
        for(MenuGrafigi altin :  altinlar){
            altin.cizdir(g);
        }
        
               for(MenuGrafigi bulut :  bulutlar){
            bulut.cizdir(g);
        }
        
        
        int offset = 10;
        g.drawImage(menuArkaplan, SecimMenusu.getX() - offset, SecimMenusu.getY() - offset, 
                SecimMenusu.getX() + SecimMenusu.getWidth() + offset, SecimMenusu.getY() + SecimMenusu.getHeight() + offset, 
                0, 0, menuArkaplan.getWidth(), menuArkaplan.getHeight(), null);
        
        
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SecimMenusu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        SecimMenusu.setOpaque(false);
        SecimMenusu.setLayout(new java.awt.GridLayout(15, 2, 20, 5));

        jLabel16.setBackground(new java.awt.Color(193, 142, 59));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel16.setText("Harita Yatay Kare Sayısı");
        SecimMenusu.add(jLabel16);

        jTextField3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("20");
        SecimMenusu.add(jTextField3);

        jLabel17.setBackground(new java.awt.Color(193, 142, 59));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel17.setText("Harita Dikey Kare Sayısı");
        SecimMenusu.add(jLabel17);

        jTextField2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("20");
        SecimMenusu.add(jTextField2);

        jLabel18.setBackground(new java.awt.Color(193, 142, 59));
        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel18.setText("Harita Altın Oranı");
        jLabel18.setToolTipText("");
        SecimMenusu.add(jLabel18);

        jSlider1.setValue(20);
        SecimMenusu.add(jSlider1);

        jLabel19.setBackground(new java.awt.Color(193, 142, 59));
        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel19.setText("Harita Gizli Altın Oranı");
        SecimMenusu.add(jLabel19);

        jSlider2.setValue(10);
        SecimMenusu.add(jSlider2);

        jLabel20.setBackground(new java.awt.Color(193, 142, 59));
        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setText("Oyuncu Başlangıç Altın Miktarı");
        SecimMenusu.add(jLabel20);

        jTextField5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("200");
        SecimMenusu.add(jTextField5);

        jLabel21.setBackground(new java.awt.Color(193, 142, 59));
        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("Hamle Adım Sayısı");
        SecimMenusu.add(jLabel21);

        jTextField6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("3");
        SecimMenusu.add(jTextField6);

        jLabel22.setBackground(new java.awt.Color(193, 142, 59));
        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel22.setText("Oyuncu A Hamle Maaliyeti");
        SecimMenusu.add(jLabel22);

        jTextField7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("5");
        SecimMenusu.add(jTextField7);

        jLabel23.setBackground(new java.awt.Color(193, 142, 59));
        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel23.setText("Oyuncu A Hedef Belirleme Maaliyeti");
        SecimMenusu.add(jLabel23);

        jTextField8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("15");
        SecimMenusu.add(jTextField8);

        jLabel24.setBackground(new java.awt.Color(193, 142, 59));
        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setText("Oyuncu B Hamle Maaliyeti");
        SecimMenusu.add(jLabel24);

        jTextField9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("5");
        SecimMenusu.add(jTextField9);

        jLabel25.setBackground(new java.awt.Color(193, 142, 59));
        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel25.setText("Oyuncu B Hedef Belirleme Maaliyeti");
        SecimMenusu.add(jLabel25);

        jTextField10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("10");
        SecimMenusu.add(jTextField10);

        jLabel26.setBackground(new java.awt.Color(193, 142, 59));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setText("Oyuncu C Hamle Maaliyeti");
        SecimMenusu.add(jLabel26);

        jTextField11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("5");
        SecimMenusu.add(jTextField11);

        jLabel27.setBackground(new java.awt.Color(193, 142, 59));
        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel27.setText("Oyuncu C Hedef Belirleme Maaliyeti");
        SecimMenusu.add(jLabel27);

        jTextField12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("15");
        SecimMenusu.add(jTextField12);

        jLabel28.setBackground(new java.awt.Color(193, 142, 59));
        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setText("Oyuncu C Gizli Altın Açma Sayısı");
        SecimMenusu.add(jLabel28);

        jTextField13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("2");
        SecimMenusu.add(jTextField13);

        jLabel29.setBackground(new java.awt.Color(193, 142, 59));
        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel29.setText("Oyuncu D Hamle Maaliyeti");
        SecimMenusu.add(jLabel29);

        jTextField14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("5");
        SecimMenusu.add(jTextField14);

        jLabel30.setBackground(new java.awt.Color(193, 142, 59));
        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel30.setText("Oyuncu D Hedef Belirleme Maaliyeti");
        SecimMenusu.add(jLabel30);

        jTextField15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("20");
        jTextField15.setToolTipText("");
        SecimMenusu.add(jTextField15);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oyun Ayarlari");

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("Oyunu Başlat");

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Çıkış");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hata Mesajları");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SecimMenusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecimMenusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SecimMenusu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    
    
    
    

}
