/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ozgeburak.yazilimlaboratuvari1;

import static com.ozgeburak.yazilimlaboratuvari1.Oyun.pencereGenislik;
import static com.ozgeburak.yazilimlaboratuvari1.Oyun.pencereYukseklik;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author burak
 */
public class SecimEkrani extends javax.swing.JPanel {

    static BufferedImage menuArkaplan;
    Timer tick;
    Thread arkaplanDongu;

    static BufferedImage altin;
    static BufferedImage bulut1, bulut2, bulut3, bulut4, bulut5;

    ArrayList<MenuGrafigi> bulutlar;
    ArrayList<MenuGrafigi> altinlar;
    Random r;

    /**
     * Creates new form SecimEkrani
     */
    public SecimEkrani() {
        //this.setPreferredSize(new Dimension(Oyun.pencereGenislik, Oyun.pencereYukseklik));
        //SecimMenusu.setOpaque(false);
        r = new Random();

        try {
            initComponents();

            //SecimMenusu.setBackground(new Color(255, 255, 255, 0));
            menuArkaplan = ImageIO.read(new File("kaynaklar/MenuArkasi.png"));
        } catch (IOException ex) {
            Logger.getLogger(SecimEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setBackground(new Color(141, 183, 242));

        try {
            altin = ImageIO.read(new File("kaynaklar/altin2x.png"));
            bulut1 = ImageIO.read(new File("kaynaklar/bulut1.png"));
            bulut2 = ImageIO.read(new File("kaynaklar/bulut2.png"));
            bulut3 = ImageIO.read(new File("kaynaklar/bulut3.png"));
            bulut4 = ImageIO.read(new File("kaynaklar/bulut4.png"));
            bulut5 = ImageIO.read(new File("kaynaklar/bulut5.png"));

        } catch (IOException ex) {
            Logger.getLogger(MenuGrafigi.class.getName()).log(Level.SEVERE, null, ex);
        }

        bulutlar = new ArrayList<MenuGrafigi>();
        altinlar = new ArrayList<MenuGrafigi>();

        for (int i = 0; i < 10; i++) {
            bulutlar.add(new MenuGrafigi(r.nextInt(1280), r.nextInt(720), "bulut"));
        }

        for (int i = 0; i < 50; i++) {
            altinlar.add(new MenuGrafigi(-200 + r.nextInt(1280 + 200), -1 * r.nextInt(720), "altin"));
        }

        tick = new Timer();
        arkaplanDongu = new Thread() {
            @Override
            public void run() {
                while (true) {
                    for (MenuGrafigi altin : altinlar) {
                        altin.guncelle();
                    }

                    for (MenuGrafigi bulut : bulutlar) {
                        bulut.guncelle();
                    }
                    repaint();
                    try {
                        Thread.sleep(1000 / 60);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SecimEkrani.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //System.out.println("test");
                }

            }
        };
        arkaplanDongu.start();

    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawRect(SecimMenusu.getX(), SecimMenusu.getY(), SecimMenusu.getWidth(), SecimMenusu.getHeight());

        for (MenuGrafigi altin : altinlar) {
            altin.cizdir(g);
        }

        for (MenuGrafigi bulut : bulutlar) {
            bulut.cizdir(g);
        }

        int offset = 10;
        g.drawImage(menuArkaplan, SecimMenusu.getX() - offset, SecimMenusu.getY() - offset,
                SecimMenusu.getX() + SecimMenusu.getWidth() + offset, SecimMenusu.getY() + SecimMenusu.getHeight() + offset,
                0, 0, menuArkaplan.getWidth(), menuArkaplan.getHeight(), null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SecimMenusu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        girdi1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        girdi2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        girdi3 = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        girdi4 = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        girdi5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        girdi6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        girdi7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        girdi8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        girdi9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        girdi10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        girdi11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        girdi12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        girdi13 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        girdi14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        girdi15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        SecimMenusu.setOpaque(false);
        SecimMenusu.setLayout(new java.awt.GridLayout(15, 2, 20, 5));

        jLabel16.setBackground(new java.awt.Color(193, 142, 59));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel16.setText("Harita Yatay Kare Sayısı(Min:5 Max:100)");
        SecimMenusu.add(jLabel16);

        girdi1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi1.setText("20");
        SecimMenusu.add(girdi1);

        jLabel17.setBackground(new java.awt.Color(193, 142, 59));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel17.setText("Harita Dikey Kare Sayısı(Min:5 Max:100)");
        SecimMenusu.add(jLabel17);

        girdi2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi2.setText("20");
        SecimMenusu.add(girdi2);

        jLabel18.setBackground(new java.awt.Color(193, 142, 59));
        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel18.setText("Harita Altın Oranı(Min:0 Max:80)");
        jLabel18.setToolTipText("");
        SecimMenusu.add(jLabel18);

        girdi3.setMaximum(80);
        girdi3.setValue(20);
        SecimMenusu.add(girdi3);

        jLabel19.setBackground(new java.awt.Color(193, 142, 59));
        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel19.setText("Harita Gizli Altın Oranı(Min:0 Max:50)");
        SecimMenusu.add(jLabel19);

        girdi4.setValue(10);
        SecimMenusu.add(girdi4);

        jLabel20.setBackground(new java.awt.Color(193, 142, 59));
        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setText("Oyuncu Başlangıç Altın Miktarı(Min:0)");
        SecimMenusu.add(jLabel20);

        girdi5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi5.setText("200");
        SecimMenusu.add(girdi5);

        jLabel21.setBackground(new java.awt.Color(193, 142, 59));
        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("Hamle Adım Sayısı(Min:1)");
        SecimMenusu.add(jLabel21);

        girdi6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi6.setText("3");
        SecimMenusu.add(girdi6);

        jLabel22.setBackground(new java.awt.Color(193, 142, 59));
        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel22.setText("Oyuncu A Hamle Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel22);

        girdi7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi7.setText("5");
        SecimMenusu.add(girdi7);

        jLabel23.setBackground(new java.awt.Color(193, 142, 59));
        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel23.setText("Oyuncu A Hedef Belirleme Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel23);

        girdi8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi8.setText("15");
        SecimMenusu.add(girdi8);

        jLabel24.setBackground(new java.awt.Color(193, 142, 59));
        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setText("Oyuncu B Hamle Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel24);

        girdi9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi9.setText("5");
        SecimMenusu.add(girdi9);

        jLabel25.setBackground(new java.awt.Color(193, 142, 59));
        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel25.setText("Oyuncu B Hedef Belirleme Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel25);

        girdi10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi10.setText("10");
        SecimMenusu.add(girdi10);

        jLabel26.setBackground(new java.awt.Color(193, 142, 59));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setText("Oyuncu C Hamle Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel26);

        girdi11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi11.setText("5");
        SecimMenusu.add(girdi11);

        jLabel27.setBackground(new java.awt.Color(193, 142, 59));
        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel27.setText("Oyuncu C Hedef Belirleme Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel27);

        girdi12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi12.setText("15");
        SecimMenusu.add(girdi12);

        jLabel28.setBackground(new java.awt.Color(193, 142, 59));
        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setText("Oyuncu C Gizli Altın Açma Sayısı(Min:0)");
        SecimMenusu.add(jLabel28);

        girdi13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi13.setText("2");
        SecimMenusu.add(girdi13);

        jLabel29.setBackground(new java.awt.Color(193, 142, 59));
        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel29.setText("Oyuncu D Hamle Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel29);

        girdi14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi14.setText("5");
        SecimMenusu.add(girdi14);

        jLabel30.setBackground(new java.awt.Color(193, 142, 59));
        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel30.setText("Oyuncu D Hedef Belirleme Maaliyeti(Min:0)");
        SecimMenusu.add(jLabel30);

        girdi15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        girdi15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        girdi15.setText("20");
        girdi15.setToolTipText("");
        SecimMenusu.add(girdi15);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Altın Toplama Oyunu");

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("Oyunu Başlat");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Çıkış");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Yanlış deger girdilerinde sınır degerler atanır. Dosyalar oyun sonu yazdırılır.");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Özge Poyraz - Burak Can Temizel");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Oyun hızını sliderı sola kaydırarak arttırabilirsiniz.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SecimMenusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecimMenusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //Değer atamalari

        try {
            if (Integer.parseInt(girdi1.getText()) < 5) {
                girdi1.setText("5");
            }
            if (Integer.parseInt(girdi1.getText()) > 100) {
                girdi1.setText("100");
            }
            Sabitler.HARITA_SUTUN = Integer.parseInt(girdi1.getText());

            if (Integer.parseInt(girdi2.getText()) < 5) {
                girdi2.setText("5");
            }
            if (Integer.parseInt(girdi2.getText()) > 100) {
                girdi2.setText("100");
            }
            Sabitler.HARITA_SATIR = Integer.parseInt(girdi2.getText());

            //Kendinden ayarli
            Sabitler.ALTIN_ORANI = girdi3.getValue();
            Sabitler.GIZLI_ALTIN_ORANI = girdi4.getValue();

            if (Integer.parseInt(girdi5.getText()) < 0) {
                girdi5.setText("0");
            }
            Sabitler.OYUNCU_ALTIN_MIKTARI = Integer.parseInt(girdi5.getText());;
            
            if (Integer.parseInt(girdi6.getText()) < 1) {
                girdi6.setText("1");
            }
            Sabitler.HAMLE_ADIM_SAYISI = Integer.parseInt(girdi6.getText());;
            
            if (Integer.parseInt(girdi7.getText()) < 0) {
                girdi7.setText("0");
            }
            Sabitler.OYUNCU_A_HAMLE_MAALIYET = Integer.parseInt(girdi7.getText());;
            
            if (Integer.parseInt(girdi8.getText()) < 0) {
                girdi8.setText("0");
            }
            Sabitler.OYUNCU_A_HEDEF_BELIRLEME_MAALIYET = Integer.parseInt(girdi8.getText());;
            
            if (Integer.parseInt(girdi9.getText()) < 0) {
                girdi9.setText("0");
            }
            Sabitler.OYUNCU_B_HAMLE_MAALIYET = Integer.parseInt(girdi9.getText());;
            
            if (Integer.parseInt(girdi10.getText()) < 0) {
                girdi10.setText("0");
            }
            Sabitler.OYUNCU_B_HEDEF_BELIRLEME_MAALIYET = Integer.parseInt(girdi10.getText());;
            
            if (Integer.parseInt(girdi11.getText()) < 0) {
                girdi11.setText("0");
            }
            Sabitler.OYUNCU_C_HAMLE_MAALIYET = Integer.parseInt(girdi11.getText());;
            
            if (Integer.parseInt(girdi12.getText()) < 0) {
                girdi12.setText("0");
            }
            Sabitler.OYUNCU_C_HEDEF_BELIRLEME_MAALIYET = Integer.parseInt(girdi12.getText());;
            
            if (Integer.parseInt(girdi13.getText()) < 0) {
                girdi13.setText("0");
            }
            Sabitler.OYUNCU_C_ACILACAK_GIZLI_ALTIN_SAYISI = Integer.parseInt(girdi13.getText());;
            
            if (Integer.parseInt(girdi14.getText()) < 0) {
                girdi14.setText("0");
            }
            Sabitler.OYUNCU_D_HAMLE_MAALIYET = Integer.parseInt(girdi14.getText());;
            
            if (Integer.parseInt(girdi15.getText()) < 0) {
                girdi15.setText("0");
            }
            Sabitler.OYUNCU_D_HEDEF_BELIRLEME_MAALIYET = Integer.parseInt(girdi15.getText());;

            //Burada oyun nesnesi oluşacak
            Oyun oyun = new Oyun();
            oyun.setPreferredSize(new Dimension(Oyun.pencereGenislik, Oyun.pencereYukseklik));

            AnaSinif.pencere.add(oyun);

            AnaSinif.pencere.pack();
            AnaSinif.pencere.setResizable(true);
            AnaSinif.pencere.setVisible(true);
            AnaSinif.pencere.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            AnaSinif.pencere.setLocationRelativeTo(null);

            AnaSinif.pencere.addComponentListener(new ComponentAdapter() {
                public void componentResized(ComponentEvent ev) {
                    Oyun.pencereGenislik = oyun.getWidth();
                    Oyun.pencereYukseklik = oyun.getHeight();
                    //oyun.oyunHizi.setBounds(pencereGenislik/2 - 60, pencereYukseklik - 25, 120, 30);
                }
            });

            arkaplanDongu.stop();
            AnaSinif.pencere.remove(this);
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SecimMenusu;
    private javax.swing.JTextField girdi1;
    private javax.swing.JTextField girdi10;
    private javax.swing.JTextField girdi11;
    private javax.swing.JTextField girdi12;
    private javax.swing.JTextField girdi13;
    private javax.swing.JTextField girdi14;
    private javax.swing.JTextField girdi15;
    private javax.swing.JTextField girdi2;
    private javax.swing.JSlider girdi3;
    private javax.swing.JSlider girdi4;
    private javax.swing.JTextField girdi5;
    private javax.swing.JTextField girdi6;
    private javax.swing.JTextField girdi7;
    private javax.swing.JTextField girdi8;
    private javax.swing.JTextField girdi9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
